plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - path: "@semantic-release/npm"
      publish: false
    - path: "@semantic-release/exec"
      prepareCmd: "npm run build"
    - "@semantic-release/git"
    - "@semantic-release/github"
