plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - path: "@semantic-release/exec"
      prepareCmd: "npm run build"
    - path: "@semantic-release/git"
      assets: ["CHANGELOG.md", "dist"]
    - "@semantic-release/github"
