name: "template-sync"
description: "Sync repositories from the template (with unrelated git history)"
branding:
    icon: git-merge
    color: green

inputs:
    token:
        description: A GitHub token with permissions to clone from other repositories. Only necessary for private templates
        required: false

runs:
    using: "node20"
    main: "dist/github-action/index.js"
