name: Release

on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed
        branches:
            - master
            - next
            - next-major
            - beta
            - alpha

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Enable corepack
              run: corepack enable

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Create a release
              uses: cycjimmy/semantic-release-action@v3
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/git
                      @semantic-release/exec
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
