name: Tests

on: [push, pull_request]

jobs:
    jest:
        name: Jest
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Enable corepack
              run: corepack enable

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test

    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Enable corepack
              run: corepack enable

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Execute prettier
              run: |
                  npx prettier . --check
                  npx eslint .
